### ISSUE TITLE
Syscall hooks functionality doesn't work on v5.15.0-1019-aws on arm64

### ISSUE THREAD

**Issue by skypodolsky** [elastio/elastio-snap#164]
An issue with memory access was seen on the v5.15.0-**1019**-aws kernel. At the same time, v5.15.0-**1009**-aws works just fine. Seems to be the problem with the specific kernel patch version.

**Comment by e-kov** [comment]
@skypodolsky 
As you wrote: everything was fine on v5.15.0-**1009**-aws. And the hooks are broken on v5.15.0-**1019**-aws. 
Perhaps there is already a newer v5.15.0-XXXX-aws kernel version. And it would be interesting to check on it. Maybe the issue is already "self-cured". :) Then the bug can be closed. And if it has not been "cured", then it is necessary to fix it.

**Comment by skypodolsky** [comment]
@e-kov yeah it's been self-cured, verified it on `5.15.0-1022-aws`. This issue can be closed.
