### ISSUE TITLE
blk_alloc_disk logic needs to be revised

### ISSUE THREAD

**Issue by skypodolsky** [elastio/elastio-snap#180]
During #176 it was seen that our approach to creating disk & request queue allocation is way too obsolete. Hence, it is necessary to update this logic to be fully compatible with the recent vision.

 - It is proposed to replace deprecated `__alloc_disk_node` with `blk_alloc_disk`
 - It is also required to reconsider the usage of the modern blk-mq API to create the request queue

**Comment by anelson** [comment]
@skypodolsky apart from the general benefit of staying up to date on kernel APIs, does this work bring us any tangible benefits?  Like better performance, potential for increased functionality, etc?

**Comment by e-kov** [comment]
> @skypodolsky apart from the general benefit of staying up to date on kernel APIs, does this work bring us any tangible benefits? Like better performance, potential for increased functionality, etc?

@anelson this bug was created as a "TODO" per my comment https://github.com/elastio/elastio-snap/pull/178#discussion_r1001599043. It does not bring any tangible benefits like performance. It just avoids usage of the non-exported kernel function. It will also help implement support for version 6 of the Linux kernel.

@skypodolsky please add other thoughts if I'm missing something.

**Comment by anelson** [comment]
Discussed on planning call.  @skypodolsky thinks this is going to be important soon for 6.x kernel compatibility.
