### ISSUE TITLE
Installing the package on Amazon Linux 2 doesn't work without previously installing kernel source packages

### ISSUE THREAD

**Issue by anelson** [elastio/elastio-snap#55]
On a fresh Amazon Linux 2 EC2 instance, I follow the instructions in `INSTALL.md`, installing the package repo and then the `dkms-elastio-snap` package.  I expect that this means I can now take snapshots of local disks, but this isn't the case:

```
$ sudo target/release/elastio block backup --scalez-stor-url http://s0test.elastio.dev:61234 /dev/nvme1n1p1 -c 8 -h 8 -s 32 -t cbt --catalog-service local
Oct 19 07:12:40.062  INFO console: Backing up 1 block device(s) to http://s0test.elastio.dev:61234/
Oct 19 07:12:40.144 ERROR console: The Elastio change block tracking driver is not available or is not supported on this system
[ec2-user@ip-172-31-13-79 elastio]$ sudo insmod elastio-snap
insmod: ERROR: could not load module elastio-snap: No such file or directory
```

Looking more closely at the installer output from when we installed the `dkms-elastio-snap` package:

```
Running transaction
  Installing : yum-plugin-dkms-build-requires-1.0-2.amzn2.noarch                                                                                           1/5
  Installing : dkms-2.6.1-1.amzn2.0.1.noarch                                                                                                               2/5
  Installing : dkms-elastio-snap-0.10.13-1.amzn2.noarch                                                                                                    3/5
Loading new elastio-snap-0.10.13 DKMS files...
Building for 4.14.193-149.317.amzn2.x86_64
Module build for kernel 4.14.193-149.317.amzn2.x86_64 was skipped since the
kernel headers for this kernel does not seem to be installed. 
  Installing : libelastio-snap-0.10.13-1.amzn2.x86_64                                                                                                      4/5
  Installing : elastio-snap-utils-0.10.13-1.amzn2.x86_64                                                                                                   5/5
Configuring dracut, please wait...
  Verifying  : dkms-2.6.1-1.amzn2.0.1.noarch                                                                                                               1/5
  Verifying  : elastio-snap-utils-0.10.13-1.amzn2.x86_64                                                                                                   2/5
  Verifying  : libelastio-snap-0.10.13-1.amzn2.x86_64                                                                                                      3/5
  Verifying  : dkms-elastio-snap-0.10.13-1.amzn2.noarch                                                                                                    4/5
  Verifying  : yum-plugin-dkms-build-requires-1.0-2.amzn2.noarch                                                                                           5/5

Installed:
  dkms-elastio-snap.noarch 0:0.10.13-1.amzn2                                    elastio-snap-utils.x86_64 0:0.10.13-1.amzn2

Dependency Installed:
  dkms.noarch 0:2.6.1-1.amzn2.0.1            libelastio-snap.x86_64 0:0.10.13-1.amzn2            yum-plugin-dkms-build-requires.noarch 0:1.0-2.amzn2

Complete!
```

Note this line in particular:

```
Module build for kernel 4.14.193-149.317.amzn2.x86_64 was skipped since the
kernel headers for this kernel does not seem to be installed. 
```

That's annoying.  Why wasn't this one of the package's dependencies?  Fine I'll do it myself.

```
$ sudo yum install kernel-headers
Loaded plugins: dkms-build-requires, extras_suggestions, langpacks, priorities, update-motd
195 packages excluded due to repository priority protections
Package kernel-headers-4.14.198-152.320.amzn2.x86_64 already installed and latest version
Nothing to do
```

What fresh hell is this??

```
$ sudo yum install kernel-devel-$(uname -r)
```

Aha that fixed the problem.

This package should have been a dependency then.

I don't know if this impacts other RHEL-derived distros but it definitely impacts Amazon Linux 2.

**Comment by e-kov** [comment]
@anelson 
There are few thoughts on it:
1) This issue is very similar to the resolved issue https://github.com/elastio/elastio-snap/issues/12
And it was resolved for CentOS/RHEL and Fedora but not for Amazon Linux, see the [change](https://github.com/elastio/elastio-snap/pull/15/files).
2) Unfortunately dependency on the `kernel-devel-uname-r` doesn't resolve the issue or even breaks installation when:
= running a chrooted system or docker image;
= running not the most recent kernel installed in the system.
Let's say, I have an Amazon Linux 2 instance. I'm running `dnf update`. It installs new kernel. Then, without reboot to the new kernel, I'm installing elastio-snap. If it has a dependency of the `kernel-devel-uname-r` but not the `kernel-devel`, it'll install a kernel-devel for the current running kernel. Then system is rebooted with the most recent kernel and kernel-devel is missing for it.

As far as I see by `sudo yum --showduplicates search kernel-devel` and `sudo yum --showduplicates search kernel` commands, hhere are 62 kernels are available starting from 4.9.62-10 up to 4.14.198-152.320 as well as kernel-devel and kernel-headers packages for these kernels. That's cool and it looks like there is no typical CentOS/RHEL problem, when kernel devel package for this not most recent kernel isn't available in the repositories when it's already moved to the Vault repo.
More thoughts about problems when kernel-debug-devel is installed instead of the kernel-devel and absence of the "weack" dependencies as "Recommends" statement in the spec file see in the comments for the issue #12.

Having all of that information, my preference is to add `kernel-devel`, but not the `kernel-devel-uname-r` dependency to the `dkms-elastio-snap` package for Amazon Linux 2 as a fix of this bug.
Adam, do you agree with it?
As an option, I can add both `kernel-devel` and `kernel-devel-uname-r` specifically for the Amazon Linux. However it'll break installation in a "chroot-ed" system or a docker container, but doesn't hurt for the EC2 instances and VMs.

**Comment by anelson** [comment]
> Adam, do you agree with it?

Yes sure.  I don't have a strong opinion about how to fix it, just that it should be fixed )

**Comment by e-kov** [comment]
Update for the previous comment.
1) I was wrong regarding the `kernel-devel` dependency in the `dkms-elastio-snap` package for Amazon Linux 2. It's already present because `%rhel` rpm macro is present and returns `7`. Expected.
2) I managed to reproduce this issue using the Amazon 2 Vagrant box.
**Preconditions:** 
- 2 kernels are installed,
- kernel-devel package is installed. yum/dnf always installs kernerl-devel with the version of the newer installed kernel.
- The system is booted with the older kernel w/o kernel-devel for it.

As result, I got the same behavior as you described. The `kernel-devel` for the current (older) kernel is not installed during the `dkms-elastio-snap` because dependency already present (but for newer kernel).
and 
- no `kernel-devel` package installed in the same transaction.
- The message appears: 
```
Module build for kernel current_kernel_ver.amzn2.x86_64 was skipped since the
kernel headers for this kernel does not seem to be installed. 
```
So I am going to add the `kernel-devel-uname-r` dependency specifically for Amazon Linux, as it is quite rare that someone would need to install elastio-snap inside a docker image where the kernel drivers are not working or when chroot into a Amazon instance...

**Comment by e-kov** [comment]
**Conclusion**
- Adding `Requires: kernel-devel-uname-r` installs `kernel-devel` package of the most recent version, but not of the current kernel version.
- Adding `Requires: kernel-devel-uname-r = %(unmae -r)` installs `kernel-devel` package of the version equal to the running kernel during the rpm build, but not during the rpm install.
- There is no way (or I didn't found it yet) to specify version of the running kernel during installation to the `Requires` statement for the `kernel-devel-uname-r`. In other words, statement `Requires: kernel-devel-uname-r = RUNTIME_KERNEL_VER` (where `RUNTIME_KERNEL_VER` is the version of the kernel running at the moment of installation) could fix the issue. But there is no way how to determine kernel version at runtime. Different shell script commands or snippets doesn't work. rpm build requires a constant there.

So, in a nutshell, there is no possible fix of this bug by means of RPM spec change.
What can I do in this situation?
- Update [INSTALL.md](https://github.com/elastio/elastio-snap/blob/master/INSTALL.md) with instruction to run manually `yum install kernel-devel-$(uname -r)` before installation of the `dkms-elastio-snap` package in case if Amazon Linux 2 runs not the most recent available kernel version.
- Try to automate it in ours Amazon EC2 deployment script.
- In future, implement an installation script or configuration utility, which will install and/or configure kernel module, install this tricky dependency of the `kernel-devel` for Amazon Linux; enable Vault repo, if necessary for the `kernel-devel` installation for not a fresh kernel for CentOS; maybe compile in advance kernel module for all installed kernels at the system (do DKM's work in advance) etc.
