### ISSUE TITLE
Implement snapshot cancellation functionality in the elastio-snap

### ISSUE THREAD

**Issue by JusSergey** [elastio/elastio-snap#92]
It is needed if the backup was aborted but the old snapshot wasn't deleted. So, for now, when the new block backup is being run we need to start from the base backup.

In the driver should be some functionality that allows us cancel the old snapshot and take the new one with all changes since the last successful backup

**Comment by e-kov** [comment]
There is no need to implement this functionality due to the following result of the investigation.
CoW file is 10% of a device while a snapshot is active. And then it is shrunk to the size of 2% of itself or 0.2% of the device. Thus, let's say, we have 10 failed ingests. And 10 shrunk CoW files consume just 2% of the device's size. It's quite acceptable. We can proceed with the appropriate changes in Elastio CLI w/o changes in driver.
Any way we were trying to find some way to re-use a shrunk CoW file after failed ingest during the next ingest. In this case we'll not need additional space at the disk at all. And CLI should not merge bitmaps in a loop.The existing IOCTLs are not suitable for this purpose. And implementation of the new IOCTL doesn't worth it, because the shrunk CoWs are very small.
The user-space consumer (Elastio CLI in our case) should just get lists of the changed blocks from all CoW files one by one and then read all of that blocks from the active snapshot device.
